### PR TITLE
Added CI and badges

### LINKED ISSUE #3: Consider adding CI?
Hi there,

👋 I've been running [zizmor](https://woodruffw.github.io/zizmor/) across the varios Rustls org repos this morning and was surprised when I came to this repo that there's no CI at all.

Is that something you've considered adding? There's a lot of example configuration to draw from across the other Rustls org repos.

### PR DESCRIPTION
**Pull request by ancwrd1**
That fixes #3

### CODE REVIEW

**Comment by cpu** [comment]
Thanks! Here's a quick follow-up tweak (https://github.com/rustls/rustls-cng/pull/5) like ones I've been landing elsewhere (https://github.com/rustls/tokio-rustls/pull/96, https://github.com/rustls/rustls-platform-verifier/pull/154, etc)

**Comment by ancwrd1** [comment]
While I have your attention here :)
Any hint to how fix docs.rs?
https://docs.rs/crate/rustls-cng/0.5.1/builds/1389786

**Comment by cpu** [comment]
> Any hint to how fix docs.rs?

Hmmm. I know we've had trouble with `docs.rs` and aws-lc-rs w/ FIPS mode enabled in the past (c.f. https://github.com/rustls/rustls/pull/1827) but I see you're already configuring just the `ring` feature here: https://github.com/rustls/rustls-cng/blob/ad3bfb3a4602b6a80eecbf28713dc432bf5d7183/Cargo.toml#L17

I wonder if it's a similar problem but with respect to the explicit `x86_64-pc-windows-gnu` target in your docs.rs config requiring extra tools for aws-lc-sys to build that aren't present on the host. I'm still not sure why it would matter given you disabled default features on rustls and build with only ring enabled :thinking: 

@ctz Does the [build error trace](https://docs.rs/crate/rustls-cng/0.5.1/builds/1389786) ring any bells for you?

**Comment by ancwrd1** [comment]
I just added it today to the manifest file in a naive attempt to fix it, but I am not sure it will work and I don't want to publish a new release just to test it.

**Pull request merged**
